### ISSUE TITLE
banking website

### ISSUE THREAD

**Issue by Oba-Asia** [Oba-Asia/globuscredit.us#1]
Thanks! Here’s a **basic banking website script** (HTML/CSS/JS only) with the following features:

* **Homepage**
* **Login Page**
* **Dashboard (dummy content)**
* Fully responsive, clean modern UI
* No backend (safe for demos/portfolios)

---

### ✅ Technologies used:

* HTML5
* CSS3 (with flexbox)
* JavaScript (for basic UI handling)

---

### 📁 File Structure

```
/banking-demo
│
├── index.html        // Homepage
├── login.html        // Login Page
├── dashboard.html    // Dashboard after login
├── style.css         // Shared stylesheet
└── script.js         // Dummy login script
```

---

### `index.html`

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Globus Bank</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <header>
    <h1>Globus Bank</h1>
    <nav>
      <a href="index.html">Home</a>
      <a href="login.html">Login</a>
    </nav>
  </header>

  <main>
    <section class="hero">
      <h2>Banking Made Easy</h2>
      <p>Secure, smart, and seamless banking for everyone.</p>
      <a class="btn" href="login.html">Get Started</a>
    </section>
  </main>

  <footer>
    <p>&copy; 2025 Globus Bank. All rights reserved.</p>
  </footer>
</body>
</html>
```

---

### `login.html`

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Login - Globus Bank</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <div class="login-container">
    <h2>Login to Your Account</h2>
    <form id="loginForm">
      <input type="text" id="username" placeholder="Username" required>
      <input type="password" id="password" placeholder="Password" required>
      <button type="submit">Login</button>
    </form>
    <p id="loginError" class="error-msg"></p>
  </div>

  <script src="script.js"></script>
</body>
</html>
```

---

### `dashboard.html`

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Dashboard - Globus Bank</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <header>
    <h1>Welcome, Customer</h1>
    <nav>
      <a href="index.html">Home</a>
      <a href="login.html">Logout</a>
    </nav>
  </header>

  <main>
    <section class="dashboard">
      <h2>Account Summary</h2>
      <p><strong>Balance:</strong> ₦450,000.00</p>
      <p><strong>Account Number:</strong> 1234567890</p>
    </section>
  </main>
</body>
</html>
```

---

### `style.css`

```css
body {
  font-family: Arial, sans-serif;
  margin: 0;
  background-color: #f4f6f8;
  color: #333;
}

header {
  background-color: #004080;
  color: white;
  padding: 1rem 2rem;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

nav a {
  color: white;
  margin-left: 1rem;
  text-decoration: none;
}

.hero {
  padding: 4rem 2rem;
  text-align: center;
}

.btn {
  background-color: #004080;
  color: white;
  padding: 0.75rem 1.5rem;
  border: none;
  text-decoration: none;
  font-weight: bold;
}

.login-container {
  max-width: 400px;
  margin: 5rem auto;
  background: white;
  padding: 2rem;
  border-radius: 8px;
  box-shadow: 0 0 10px #ccc;
}

input {
  width: 100%;
  padding: 0.75rem;
  margin: 0.5rem 0;
}

button {
  width: 100%;
  padding: 0.75rem;
  background-color: #004080;
  color: white;
  border: none;
  cursor: pointer;
}

.error-msg {
  color: red;
  margin-top: 1rem;
  text-align: center;
}
```

---

### `script.js`

```js
document.addEventListener("DOMContentLoaded", function () {
  const form = document.getElementById("loginForm");
  const errorMsg = document.getElementById("loginError");

  if (form) {
    form.addEventListener("submit", function (e) {
      e.preventDefault();
      const username = document.getElementById("username").value;
      const password = document.getElementById("password").value;

      // Dummy login check
      if (username === "admin" && password === "1234") {
        window.location.href = "dashboard.html";
      } else {
        errorMsg.textContent = "Invalid login credentials.";
      }
    });
  }
});
```

---

Would you like a downloadable zip folder, or want me to help you host this on GitHub Pages or Netlify?
